# https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: pip install --upgrade pip; pip install .[tests]
      - run:
          name: Run unittests
          command: pytest

  run-examples:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: pip install --upgrade pip; pip install .[doc]
      - run:
          # The report example requires a lot of RAM. Since we only want to
          # check the syntax, we change the parameters for the execution in
          # the CI so that only little RAM is consumed.
          name: Generate report tex-file
          command: >
            echo -e \
              '#!/bin/bash\n' \
              'echo -n "Replace the unique line \"${1}\" with \"${2}\"" && ' \
              'sed -i "/^${1}\\$/{s//${2}/;x;/./{q1};x;h};\\${x;/./{x;q0};x;q1}" doc/examples/sample_report.py && ' \
              'echo -e "\\033[1;32m Success\\033[0m" && exit 0 || ' \
              'echo -e "\\033[1;31m Fail\\033[0m" && exit 1' \
                > ~/.local/bin/update_sample_report.sh;
            chmod +x ~/.local/bin/update_sample_report.sh;
            update_sample_report.sh "width = 640" "width = 32";
            update_sample_report.sh "height = 480" "height = 24";
            update_sample_report.sh "steps = 50" "steps = 10";
            set -o xtrace;
            cat doc/examples/sample_report.py;
            python doc/examples/sample_report.py
      - persist_to_workspace:
          root: .
          paths:
            - myreport

  compile-report:
    docker:
      - image: texlive/texlive:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Compile report tex-file
          command: cd myreport; set -o xtrace; ls -laR; cat -n report.tex; latexmk --pdflatex report.tex

workflows:
  unittests:
    jobs:
      - run-tests
  create-report:
    jobs:
      - run-examples
      - compile-report:
          requires:
            - run-examples
