# https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: pip install --upgrade pip; pip install .[tests]
      - run:
          name: Run unittests
          command: pytest

  run-examples:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: pip install --upgrade pip; pip install .[doc]
      - run:
          name: Install CI doc test files
          command: set -o xtrace; cp .circleci/test_doc_examples/ci_test_*.py doc/examples/
      - run:
          name: Generate report tex-file
          command: python doc/examples/ci_test_sample_report.py
      - persist_to_workspace:
          root: .
          paths:
            - myreport

  compile-report:
    docker:
      - image: texlive/texlive:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Compile report tex-file
          command: cd myreport; set -o xtrace; ls -laR; cat -n report.tex; latexmk --pdflatex report.tex

workflows:
  unittests:
    jobs:
      - run-tests
  create-report:
    jobs:
      - run-examples
      - compile-report:
          requires:
            - run-examples
